clusterName: "cassandra-pmem-test-cluster"
#replica count specfies how many nodes will be used when deploying the cassandra-pmem cluster
replicaCount: 4
statefulSetSuffix: cassandra-pmem-cluster
appLabelSuffix: cassandra-pmem

#If set to true, the JMX port is also exposed as part of the service
#Please notice that exposing the port requires to setup authentication
#this can be accomplished providing the files using "enableAdditionalFilesConfigMap: true"
#The additional files inside <helm-chart-dir>/files/additionalFiles is mounted inside the pod
#on /etc/cassandra so additional files such as auth files for JMX can be added, by default some basic testing files are provided 
#for production-like configuration some additional configuration needs to be done
exposeJmxPort: true
enableAdditionalFilesConfigMap: true

#If set to true a NodePort service will be deployed to expose the cluster externally
exposeClusterExternally: false

image:
  repository: DOCKER_CASSANDRA_PMEM_REGISTRY
  tag: latest
  pullPolicy: IfNotPresent
  name: CASSANDRA_IMAGE

#Pool size should be ~ containerPmemAllocation - 2G, otherwise pmem cassandra wil fail allocating heap,
#this is because filesystem metadata use a portion of the total space requested in the persisten volume claim
pmem:
  containerPmemAllocation: "4G"
  fsdaxPoolSizeInGB: "3"

#Non-Pmem resources to be used by each cassandra-pmem node
resources:
  enabled: true
  requests:
    memory: "5G"
    cpu: "1"
  limits:
    memory: "6G"
    cpu: "4"

#Variable used to control JVM_OPTS for the pods
jvmOpts: 
  enabled: true
  value: "-Xms4G -Xmx4G -Xmn2G"

#If enablePersistence is set to false, the data and logs dir will be using no K8s persistent volumes
#therefore the data on the cluster does not persist across container deletion and recreation, this option
#is useful for testing purposes
#
#custom storage classes can be used for data and logs, on a real world scenario it is prefered 
#to use two different local storage devices in order to avoid bottlenecks and high network load
enablePersistence: true
persistentVolumes:
  logsVolumeSize: 4G
  dataVolumeSize: 4G
  logsStorageClass: K8S_LOCAL_STORAGE_CLASS
  dataStorageClass: K8S_LOCAL_STORAGE_CLASS

#When set to true, the chart mounts the files stored in <helm-chart-dir>/files/conf as a read-only volume mounted in /workspace/cassandra/conf inside the pods. More complex
#configurations can be provided in this way
provideCustomConfig: false

#Enable deploying a cassandra image containing client tools to test against the main cluster
#this image is run as an independent pod from the main deployment, also test profiles can be placed under
#the directory <helm-chart-dir>/files/testProfiles and those are  mounted on /testProfiles inside the client tools pod
enableClientToolsPod: true
clientToolsImage:
  repository: DOCKER_CLIENT_TOOLS_REGISTRY
  tag: latest
  pullPolicy: IfNotPresent
  image: CLIENT_TOOLS_IMAGE

