apiVersion: databases.spotahome.com/v1
kind: RedisFailover
metadata:
  name: redisfailover-pmem
spec:
  sentinel:
    replicas: 3
    command:
      - "redis-server"
      - "/redis/sentinel.conf"
      - "--sentinel"
      - "--protected-mode"
      - "no"
  redis:
    securityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
    replicas: 3
    image: PMEM_REDIS_IMAGE
    command:
      - "redis-server"
      - "/redis/redis.conf"
      - "--nvm-maxcapacity"
      - "200"
      - "--nvm-dir"
      - "/data"
      - "--nvm-threshold"
      - "44"
      - "--protected-mode"
      - "no"
      - "--dir"
      - "/tmp"
    storage:
      persistentVolumeClaim:
        metadata:
          name: redisfailover-pmem-data
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 100Mi
          storageClassName: pmem-csi-sc-ext4
