apiVersion: v1
kind: ConfigMap
metadata:
  name: tomcat-conf
data:
  index.jsp: |
    hello,tomcat!

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: my-tomcat
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: my-tomcat
    spec:
      containers:
      - name: my-tomcat
        image: docker.io/clearlinux/tomcat
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: config-volume        
          mountPath: /usr/share/apache-tomcat/webapps/ROOT/index.jsp
          subPath: index.jsp
      volumes:
      - name: config-volume
        configMap:
          name: tomcat-conf

---
apiVersion: v1
kind: Service
metadata:
  name: my-tomcat
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30001
  selector:
    app: my-tomcat

