apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-php
  labels:
    app: php-fpm
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-redis
  labels:
    app: php-fpm
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
