version: '2'

services:
  openvino:
    image: clearlinux/openvino:latest
    environment:
      http_proxy: $http_proxy
      https_proxy: $https_proxy
      MODEL_NAME: alexnet
      MODEL_PRECISION: FP32
    volumes:
      - "./cat.bmp:/app/cat.bmp"
      - "./demo.sh:/app/demo.sh"
    command: "/app/demo.sh"

