version: '2'

services:
  openvino:
    image: clearlinux/openvino:latest
    environment:
      http_proxy: $http_proxy
      https_proxy: $https_proxy
      MODEL_NAME: mobilenetv2-int8-tf-0001
      MODEL_PRECISION: FP32
    ports:
      - "5000:5000"
    volumes:
      - "./app.py:/app/app.py"
    command: "python3 app.py"

