apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: memcached
spec:
  replicas: 1
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        run: memcached
    spec:
      containers:
      - name: memcached
        image: docker.io/clearlinux/memcached
        ports:
        - containerPort: 11211

---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: memcached
  name: memcached
spec:
  type: NodePort
  ports:
  - port: 11211
    protocol: TCP
    targetPort: 11211
    nodePort: 30100
  selector:
    run: memcached

