#!/bin/bash
echo "=> Tagging the image"

. ../docker-hooks.sh

image="clearlinux/memcached"
tag=$(get_tag memcached)

if [ $? -eq 0 ] && [ -n "$tag" ]; then
    # major tag format like 1.4 or 1.5
    major_tag=${tag%.*}
    tag_and_push $tag $major_tag
fi
