#!/bin/bash
echo "=> Tagging the image"

. ../docker-hooks.sh

image="clearlinux/httpd"
tag=$(get_tag httpd)

if [ $? -eq 0 ] && [ -n "$tag" ]; then
    major_tag=${tag%%.*}
    tag_and_push $tag $major_tag
fi
