kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-1
  labels:
    type: local
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/pv-1"
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-2
  labels:
    type: local
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/pv-2"
