apiVersion: v1
kind: Service
metadata:
  {{- $serviceName := printf "%s-cassandra-pmem-svc" .Release.Name  }}
  name: {{ $serviceName }}
  labels:
    {{- $appLabel := printf "%s-%s" .Release.Name .Values.appLabelSuffix }}      
    app: {{ $appLabel }}
spec:
  ports:
  - port: 9042
    name: cql
  - port: 7000
    name: inter-node 
  {{- if .Values.exposeJmxPort }}
  - port: 7199
    name: jmx-port
  {{- end }}
  clusterIP: None
  selector:
    app: {{ $appLabel }}
