{{- if .Values.exposeClusterExternally }}
apiVersion: v1
kind: Service
metadata:
  {{- $serviceName := printf "%s-cassandra-pmem-service" .Release.Name  }}
  name: {{ $serviceName }}
  labels:
    {{- $appLabelSvc := printf "%s-%s" .Release.Name .Values.appLabelSuffix }}
    app: {{ $appLabelSvc }}
spec:
  nodePort: 30001
  type: NodePort
  ports:
  - name: cql
    port: 9042
    targetPort: cql
  - name: thrift
    port: 30001
    targetPort: thrift
  selector:
    app: {{ $appLabelSvc }}
{{- end }}
