{{- if and (.Files.Glob "files/testProfiles/*") (.Values.enableClientToolsPod) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-test-profiles-configmap
  labels:
    app: {{printf "%s-%s" .Release.Name .Values.appLabelSuffix }}
data: 
  {{ (.Files.Glob "files/testProfiles/*").AsConfig | nindent 2 }}
{{- end }}
