export no_proxy=10.0.0.0/8,192.168.0.0/16,localhost,127.0.0.0/8,134.134.0.0/16,ciao-dev.example.com
export PATH=$GOBIN:$PATH
export TERM=xterm

# OpenStack rc file
if [ -f /root/openrc ];
then
  . /root/openrc
fi

# CIAO rc file
if [ -f /root/ciaorc ];
then
  . /root/ciaorc
fi