apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
data:
  my.cnf: |
    [mysqld]

    skip-log-bin
    ssl=0

    table_open_cache = 200000
    table_open_cache_instances=64
    back_log=3500
    max_connections=4000

    innodb_file_per_table

    innodb_log_file_size=10G
    innodb_log_files_in_group=2
    innodb_log_buffer_size=64M

    innodb_open_files=4000

    innodb_buffer_pool_size= 100G
    innodb_buffer_pool_instances=8

    innodb_flush_log_at_trx_commit = 1
    innodb_doublewrite=1
    innodb_flush_method = O_DIRECT
    innodb_file_per_table = 1
    innodb_io_capacity=2000
    innodb_io_capacity_max=4000
    innodb_flush_neighbors = 0
    innodb_use_native_aio=1

    join_buffer_size=256K
    sort_buffer_size=256K
