#!/bin/bash
echo "=> Tagging the image"

. ../docker-hooks.sh

image="clearlinux/haproxy"
tag=$(get_tag haproxy)

if [ $? -eq 0 ] && [ -n "$tag" ]; then
    # major tag format 1.6 or 2.0
    major_tag=${tag%.*}
    tag_and_push $tag $major_tag
fi
