#!/bin/bash
set -eo pipefail

host="$(hostname --ip-address || echo '127.0.0.1')"
port="$(cat /workspace/cassandra/conf/cassandra.yaml | grep 'native_transport_port:' | tail -1 | awk '{print $2}' || echo '9042' )"

if /workspace/cassandra/bin/cqlsh "$host" "$port" < /dev/null; then
	exit 0
fi

exit 1
