#!/bin/bash
echo "=> Tagging the image"

. ../docker-hooks.sh

image="clearlinux/python"
tag=$(get_tag python3)

if [ $? -eq 0 ] && [ -n "$tag" ]; then
    # major tag format x.y, such as 3.6 , 3.7
    major_tag=${tag%.*}
    tag_and_push $tag $major_tag
fi
