#!/bin/bash
echo "=> Tagging the image"

. ../docker-hooks.sh

image="clearlinux/tensorflow-serving"
tag=$(get_tag tensorflow-serving)

if [ $? -eq 0 ] && [ -n "$tag" ]; then
    # major tag format x.y, such as 1.14
    major_tag=${tag%.*}
    tag_and_push $tag $major_tag
fi
