apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
data:
  redis.conf: |
    maxmemory 2mb
    maxmemory-policy allkeys-lru

---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: valkey-deployment
spec:
  replicas: 1
  template:
    metadata:
      name: valkey-deployment
      labels:
        app: valkey
    spec:
      volumes:
        - name: config-volume
          configMap:
            name: valkey-config
      containers:
      -  image: ghcr.io/clearlinux/valkey
         name: valkey
         command: ["valkey-server"]
         args: ["/etc/redis.conf","--protected-mode no"]
         volumeMounts:
           - name: config-volume
             mountPath: /etc/redis.conf
             subPath: redis.conf

---
apiVersion: v1
kind: Service
metadata:
  name: valkey-svc
spec:
  type: NodePort
  ports:
  - port: 6379
    targetPort: 6379
    nodePort: 30001
  selector:
    app: valkey
