apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: valkey-deployment
spec:
  replicas: 1
  template:
    metadata: 
      name: valkey-deployment
      labels:
        app: valkey
    spec:
      containers:
      -  image: ghcr.io/clearlinux/valkey
         name: valkey

---
apiVersion: v1
kind: Service
metadata:
  name: valkey-svc
spec:
  type: NodePort
  ports:
  - port: 6379
    targetPort: 6379
    nodePort: 30001
  selector:
    app: valkey

