apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: cassandra
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: cassandra
    spec:
      containers:
        - image: docker.io/clearlinux/cassandra
          name: cassandra
          env:
            - name: CASSANDRA_DISK_FAILURE_POLICY
              value: start      
            - name: CASSANDRA_NUM_TOKENS
              value: "255"
            - name: CASSANDRA_CLUSTER_NAME
              value: my_Cassandra
            - name: CASSANDRA_DC
              value: DC1
            - name: CASSANDRA_RACK
              value: Kubernetes Cluster
            - name: CASSANDRA_ENDPOINT_SNITCH
              value: GossipingPropertyFileSnitch
          ports:
            - containerPort: 9042
              name: cql

---
apiVersion: v1
kind: Service
metadata:
  name: cassandra-svc
spec:
  type: NodePort
  ports:
  - port: 9042
    targetPort: 9042
    nodePort: 30001
  selector:
    name: cassandra

