#!/bin/bash
echo "=> Tagging the image"

. ../docker-hooks.sh

image="clearlinux/redis"
tag=$(get_tag redis-native)

if [ $? -eq 0 ] && [ -n "$tag" ]; then
    set -e
    docker tag $image:latest $image:$tag
    docker push $image:$tag
    major_tag=${tag%%.*}
    docker tag $image:latest $image:$major_tag
    docker push $image:$major_tag
fi
